apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: jjoisyousef/nodejs-k8s-eks-cicd:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
